---
title: "Applied DS lab"
author: "Huiting Sun"
date: "07/08/2019"
output: html_document
---

# lab 1

```{r}
library(tmaptools)
setwd("/Users/apple/Desktop/Applied DS")
mydata = read.csv("NYCTaxiData.csv")
map<-get_stamenmap(rbind(as.numeric(paste(geocode_OSM("Manhattan")$bbox))), zoom = 11)
ggmap(map)
```

```{r}
ggmap(map) + geom_point(aes(x = pickup_longitude, y = pickup_latitude), colour="white", size = 0.01, data = mydata, alpha = .5)
```


# lab 2
# Square Binning
```{r}
plotmap <- ggmap(map) + geom_bin2d(bins=100, data=mydata, aes(x =
pickup_longitude, y = pickup_latitude))
plotmap
```

# Hex Binning
```{r}
install.packages("hexbin")
```

```{r}
plotmap <- ggmap(map) + coord_cartesian() + geom_hex(bins=100, data=mydata,
aes(x = pickup_longitude, y = pickup_latitude)) + coord_fixed(1.3)
plotmap
```


# SparkR
```{r}
install.packages("sparklyr")
library(sparklyr)
spark_install(version = "2.1.0")
```

```{r}
library(sparklyr)
spark_install(version = "2.1.0")
#Sys.setenv(JAVA_HOME = "/usr/lib/jvm/java-8-openjdk-amd64/jre")
Sys.setenv(JAVA_HOME = "/Library/Java/JavaVirtualMachines/jdk1.8.0_221.jdk/Contents/Home")
library(sparklyr)
library(dplyr)
```

```{r}
sc <- spark_connect(master = "local")
```

```{r}
nyc_taxi <- spark_read_csv(sc, name = "taxi_data", path = "NYCTaxiData.csv", header = TRUE, delimiter = ",")
```

# Manual Square Binning by Rounding
```{r}
nyc_taxi <- nyc_taxi %>%
mutate(pickup_latitude = round(pickup_latitude,3))%>%
mutate(pickup_longitude = round(pickup_longitude,3))%>%
sdf_register("nyc_taxi")
```

```{r}
nyc_taxi_summary <- nyc_taxi %>%
group_by(pickup_latitude, pickup_longitude) %>%
summarise(n=n()) %>%
sdf_register("nyc_taxi_summary")
```

```{r}
nyc_taxi_summary
```

```{r}
spark_write_csv(nyc_taxi_summary,"summary",header=TRUE,delimiter=",", mode="overwrite")

plotmap <- ggmap(map) + geom_point(aes(x = pickup_longitude, y =
pickup_latitude, colour=n,
fill=n), data = nyc_taxi_summary,
shape=22, size=0.25)
ggsave("plot.png")
```

