---
title: "project1"
author: "Huiting Sun"
date: "11/08/2019"
output: word_document
---

```{r cars}
setwd("/Users/apple/Desktop/Applied DS/project1")
mydata = read.csv("combined_csv.csv")
```

```{r cars}
library(dplyr)
filter_mydata <- filter(mydata, trip_distance != 0.00)
filter_mydata <- filter(filter_mydata, tip_amount >= 0.00)
filter_mydata <- filter(filter_mydata, tip_amount < 300)
filter_mydata <- filter(filter_mydata, dropoff_longitude != 0.00)
```

```{r}
filter_mydata
```

```{r cars}
library(tmaptools)
library(ggmap)
map<-get_stamenmap(rbind(as.numeric(paste(geocode_OSM("New York")$bbox))), zoom = 11)
ggmap(map)
```

# geom point
```{r}
ggmap(map) + geom_point(aes(x = dropoff_longitude, y = dropoff_latitude), colour="lightblue1", size = 0.01, data = filter_mydata, alpha = .5)
```

# Square Binning
```{r cars}
plotmap <- ggmap(map) + geom_bin2d(bins=60, data=filter_mydata, aes(x =
dropoff_longitude, y = dropoff_latitude))
plotmap
```

# Hex Binning
```{r cars}
ggmap(map) + coord_cartesian() + geom_hex(bins=60, data=filter_mydata,
 aes(x = dropoff_longitude, y = dropoff_latitude)) + labs(fill="Drop-off count", title = "Taxi Drop-off distribution of New York City")
```

# Drop-off location
```{r}
library(plotly)
plotmap <- ggmap(map) + coord_cartesian() + geom_hex(bins=60, data=filter_mydata, aes(x = dropoff_longitude, y = dropoff_latitude)) + scale_fill_gradient(low="lightblue1",high="darkblue",trans="log10") +
  labs(title = "Taxi Drop-off location Distribution of New York City",
       x = "longitude",
       y = "latitude",
       fill = "count")
ggplotly(plotmap)
```


```{r}
library(tigris)
library(dplyr)
library(leaflet)
library(sp)
library(ggmap)
library(maptools)
library(broom)
library(httr)
library(rgdal)
r <- GET('http://data.beta.nyc//dataset/0ff93d2d-90ba-457c-9f7e-39e47bf2ac5f/resource/35dd04fb-81b3-479b-a074-a27a37888ce7/download/d085e2f8d0b54d4590b1e7d1f35594c1pediacitiesnycneighborhoods.geojson')
nyc_neighborhoods <- readOGR(content(r,'text'), 'OGRGeoJSON', verbose = F)
```

```{r}
nyc_neighborhoods_df <- tidy(nyc_neighborhoods)
ggmap(map) + coord_cartesian() + geom_hex(bins=60, aes(x = dropoff_longitude, y = dropoff_latitude, fill = cut(tip_amount, c(0, 5, 10, 50, 100, 200, Inf))), data = filter_mydata, siz=1, alpha=.8) + coord_fixed(1.3) + labs(fill="Tip amount") + scale_fill_brewer(palette = "Purples") + geom_polygon(data=nyc_neighborhoods_df, aes(x=long, y=lat, group=group), color="yellow", fill=NA, alpha=.4)
```

```{r}
group <- group_by(filter_mydata, dropoff_longitude, dropoff_latitude)
per_group <- summarize(group, filter_mydata = n())
per_group
```

```{r}
nyc_neighborhoods_df <- tidy(nyc_neighborhoods)
ggmap(map) + coord_cartesian() + geom_hex(bins=60, aes(x = dropoff_longitude, y = dropoff_latitude, fill = cut(tip_amount, c(0, 5, 10, 50, 100, 200, Inf))), data = filter_mydata, siz=1, alpha=.8) + coord_fixed(1.3) + labs(fill="Tip amount") + scale_fill_brewer(palette = "Purples") 
```

```{r}
g <- ggmap(map) + stat_density2d(aes(x=dropoff_longitude, y=dropoff_latitude, fill=..level..), data=filter_mydata, geom="polygon", alpha=0.2)
g + scale_fill_gradient(low = "yellow", high = "red")
```

# Drop-off location filling with tips amount 
```{r}
library(ggmap)
ggmap(map) + coord_cartesian() + geom_hex(bins=60, aes(x = dropoff_longitude, y = dropoff_latitude, fill = cut(tip_amount, c(0, 5, 10, 50, 100, 200, Inf))), data = filter_mydata, siz=1, alpha=.8) + coord_fixed(1.3) + labs(fill="Tip amount", title = "Tip amount based on drop-off location") + scale_fill_brewer(palette = "Purples")
```

```{r}
rate <- filter_mydata$tip_amount/filter_mydata$trip_distance
ggmap(map) + coord_cartesian() + geom_hex(bins=60, aes(x = dropoff_longitude, y = dropoff_latitude, fill = cut(rate, c(0, 5, 10, 50, 100, 200, Inf))), data = filter_mydata, siz=1, alpha=.8) + coord_fixed(1.3) + labs(fill="Tip amount/mile", title = "Relationship between tip amount and trip distance") + scale_fill_brewer(palette = "Purples")
```

```{r}
rate <- filter_mydata$tip_amount/filter_mydata$passenger_count
ggmap(map) + coord_cartesian() + geom_hex(bins=60, aes(x = dropoff_longitude, y = dropoff_latitude, fill = cut(rate, c(0, 5, 10, 50, 100, 200, Inf))), data = filter_mydata, siz=1, alpha=.8) + coord_fixed(1.3) + labs(fill="Tip amount/person", title = "Relationship between tip amount and passenger count") + scale_fill_brewer(palette = "Purples")
```

```{r}
ggmap(map) + coord_cartesian() + geom_hex(bins=60, aes(x = dropoff_longitude, y = dropoff_latitude, fill = cut(trip_distance, c(0, 5, 10, 50, 100, 200, 500, Inf))), data = filter_mydata, siz=1, alpha=.8) + coord_fixed(1.3) + labs(fill="Tip amount") + scale_fill_brewer(palette = "PuRd")
```


```{r}
ggmap(map) + coord_cartesian() + geom_hex(bins=60, aes(x = dropoff_longitude, y = dropoff_latitude, colour=passenger_count), data = filter_mydata, siz=1, alpha=.8)
```

```{r}
ggmap(map) + coord_cartesian() + geom_hex(bins=60, aes(x = dropoff_longitude, y = dropoff_latitude, colour=factor(passenger_count)), data = filter_mydata, siz=1, alpha=.8)
```

```{r}
library(dplyr)
library(ggplot2)
library(ggmap)
library(ggthemes)
ggmap(map) + coord_cartesian() + geom_hex(bins=60, aes(x = dropoff_longitude, y = dropoff_latitude, colour=factor(passenger_count)), data = filter_mydata, siz=1, alpha=.8) + theme_map() + scale_fill_gradient(low="white",high="black",trans="log10")
```




```{r}
library(dplyr)
library(ggplot2)
library(ggmap)
library(ggthemes)
#mid<-mean(filter_mydata$tip_amount)
ggmap(map) + coord_cartesian() + geom_hex(bins=60, aes(x = dropoff_longitude, y = dropoff_latitude, fill = cut(tip_amount, c(0, 5, 10, 50, 100, 500, Inf))), data = filter_mydata) 
```


```{r}
ditch_the_axes <- theme(
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank()
  )
elbow_room1 <- ggmap(map) + 
      geom_polygon(data = data.frame(filter_mydata), aes(x = dropoff_longitude, y = dropoff_latitude, fill=tip_amount), color = "white") +
      geom_polygon(color = "black", fill = NA) +
      theme_bw() +
      ditch_the_axes
```

```{r}
elbow_room1
```

```{r}
ggplot(data = filter_mydata) + 
  geom_polygon(aes(x = dropoff_longitude, y = dropoff_latitude, fill = tip_amount, group = tip_amount), color = "white") + 
  coord_fixed(1.3) +
  guides(fill=FALSE)  # do this to leave off the color legend
```



```{r}
ggplot() + geom_polygon(aes(x = dropoff_longitude, y = dropoff_latitude, colour=tip_amount), data = filter_mydata, siz=1, alpha=.8) + scale_fill_gradient(low="lightblue1",high="darkblue",trans="log10")
```


# Drop-off location filling with trip distance
```{r}
ggmap(map) + coord_cartesian() + geom_hex(bins=60, aes(x = dropoff_longitude, y = dropoff_latitude, colour=trip_distance), data = filter_mydata, siz=1, alpha=.8) + scale_fill_gradient(low="lightblue1",high="darkblue",trans="log10")
```

# Drop-off location filling with passenger count
```{r}
ggmap(map) + coord_cartesian() + geom_hex(bins=60, aes(x = dropoff_longitude, y = dropoff_latitude, colour=passenger_count), data = filter_mydata, siz=1, alpha=.8) + scale_fill_gradient(low="lightblue1",high="darkblue",trans="log10")
```

# Drop-off location filling with tip_amount/trip_distance
```{r}
ggmap(map) + coord_cartesian() + geom_hex(bins=60, aes(x = dropoff_longitude, y = dropoff_latitude, colour=tip_amount/trip_distance), data = filter_mydata, siz=1, alpha=.8) + scale_fill_gradient(low="lightblue1",high="darkblue",trans="log10")
```

# Drop-off location filling with tip_amount/passenger_count
```{r}
ggmap(map) + coord_cartesian() + geom_hex(bins=60, aes(x = dropoff_longitude, y = dropoff_latitude, colour=tip_amount/passenger_count), data = filter_mydata, siz=1, alpha=.8) + scale_fill_gradient(low="lightblue1",high="darkblue",trans="log10")
```

```{r}
mydata
```

```{r}
boxplot(mydata$tip_amount, main="Tip_amount")
```

```{r}
new_mydata <- filter(filter_mydata, tip_amount <= 100)
boxplot(new_mydata$tip_amount)
```

```{r}
plot(new_mydata$tip_amount, new_mydata$passenger_count)
#print(new_mydata$tip_amount)
```
